### ISSUE TITLE
React i18next namespaces

### ISSUE THREAD

**Issue by edwingl10** [beyondhb1079/s4us#1066]
Make use of [namespace](https://www.i18next.com/principles/namespaces) in React-18next. 

For now need to make namespaces for the following: 
- [x] #1067
- [x] #1068
- [x] #1074
- [x] #1072
- [x] #1079
- [x] #1076
- [x] #1077
- [x] #1071
- [x] #1081
- [x] #1082

**Comment by josueetcom** [comment]
I would add a "common" namespace for words or phrases that might appear in multiple places
