### ISSUE TITLE
[Bug]: The entire ScholarshipCard is not clickable in More Scholarships section

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="312" alt="Screen Shot 2022-05-03 at 10 54 08 PM" src="https://user-images.githubusercontent.com/8023233/166629084-e3821e48-1da7-4e32-9375-4e6ae7dbb32b.png">

### Steps To Reproduce

1. Go to dreamscholars.org
2. Find a scholarship
3. Scroll to the bottom of its page
4. Notice how some cards are not _fully_ clickable

### What devices are you experiencing the problem on?

Desktop

### What browsers are you seeing the problem in?

Chrome

**Comment by edwingl10** [comment]
what if we make these cards smaller, all with the same size. If information doesn't fit, we can just hide it.

**Comment by josueetcom** [comment]
> what if we make these cards smaller, all with the same size. If information doesn't fit, we can just hide it.

What do you mean by smaller?
