### ISSUE TITLE
About: Gonzalo Lara

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#11]
Come up with 2-3 sentences about yourself so we can fill the [About page](https://github.com/beyondhb1079/s4us/blob/main/src/pages/About.jsx#L9)

**Comment by gonzalo1330** [comment]
My passion for computers has lead me to pursue a career in Software Engineering. I am currently a UWB CSS student completing my final year in the Computer Science and Software Engineering program. I am 24 years old, bilingual and currently in the DACA program. I intend to contribute as much as possible to building a better tomorrow.

**Comment by josueetcom** [comment]
Great! Could you add that [in the About page](https://github.com/beyondhb1079/s4us/blob/main/src/pages/About.jsx#L23)?

**Comment by gonzalo1330** [comment]
Ok I added it to the link provided and it created a pull request for it
