### ISSUE TITLE
About: Sergio Mejia

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#12]
Come up with 2-3 sentences about yourself so we can fill the [About page](https://github.com/beyondhb1079/s4us/blob/main/src/pages/About.jsx#L9)

**Comment by josueetcom** [comment]
@s-mejia14 can you come up with the 2-3 sentences for your bio?

**Comment by s-mejia14** [comment]
I’m a UX Designer that is interested in using technology as a means to solve problems. My personal experiences have inspired my focus on empathy and universal design. I find joy in the ability to explore ideas with a central aim to create solutions that will help people solve meaningful problems.
