### ISSUE TITLE
Change "Login" to "Sign Out" in header

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#15]
Currently when you go to https://dreamerscholars.web.app/ and log in, it still shows **Login** at the top. Also to sign out, you need to click an extra button instead of just the Login button.

**Comment by gonzalo1330** [comment]
Now for the login / sign out button do you want them to be swapped depending on the condition if they are logged in or not OR can they be next to each other because I got it to work being next to each other but switching the name based on the condition will be more complicated since the current file with the button does not have access to the isSignedIn state
<img width="207" alt="Screen Shot 2020-09-19 at 3 02 37 PM" src="https://user-images.githubusercontent.com/64123425/93690054-2b2c2b80-fa89-11ea-83e3-d163ffefc7b0.png">

**Comment by josueetcom** [comment]
You should be able to render one or the other based on the condition. E.g. 
```jsx
  <div>
    <Button onClick={isSignedIn ? signUserOut: showLoginDialog}>
      {isSignedIn ? "Login" : "Sign out"}
    </Button>
    <LoginDialog open={loginDialogOpen} ... />
    </div>
```

I suggest renaming the component LoginButton and refactoring the dialog into a separate class combined with the FirebaseLoginScreen. The LoginDialog shouldn't really need to do anything since it's just for logging in. It should however probably have a property indicating whether it's open based on the state of the LoginButton component. I'm imagining this flow:
- `LoginButton` component has two state variables called `isSignedIn` and `loginDialogOpen`
- `isSignedIn` is initially set depending on `firebase.auth().currentUser`
- `isSignedIn` changes due to `firebase.auth().onAuthStateChanged()`
- The Button's text and onClick listener depends on `isSignedIn`
- `loginDialogOpen` is initially false
- If `isSignedIn`, then `showLoginDialog` will set `loginDialogOpen` to true, which will make show the login dialog (which doesn't care about sign-in state)
  - Once the user logs in, this will trigger `firebase.auth().onAuthStateChanged()` which will set `isSignedIn` to `true` and `loginDialogOpen` to `false`.
- If `!isSignedIn`, then `signUserOut` will call `firebase.auth().signOut()`. This will trigger `firebase.auth().onAuthStateChanged()` which can set `isSignedIn` to `false` and `loginDialogOpen` to `false`.

Something along those lines is what I'm imagining

**Comment by gonzalo1330** [comment]
Once you've had time to review the updated code and can verify that this bug was fixed, feel free to close the issue.

**Comment by josueetcom** [comment]
Actually, you can close this automatically by [linking the related PR using a keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Then the issue will close when the PR is merged

**Comment by josueetcom** [comment]
There's ways to [manually link them](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue) as well

**Comment by gonzalo1330** [comment]
Got it, ill go ahead and close this and moving forward ill link issues with PR so that they can get closed on it merges.
