### ISSUE TITLE
Site Footer

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#18]
Modify [Footer.jsx](https://github.com/beyondhb1079/s4us/blob/main/src/components/Footer.jsx) to match the styling/layout in the Figma designs for [desktop](https://www.figma.com/file/nwrW3UebcvSWyQZGb5ixNr/DreamScholar?node-id=562%3A1393) and [mobile](https://www.figma.com/file/bySglSmoHWErgM39v9dWcj/undocuScholarMobile?node-id=236%3A273) and add appropriate links.

You'll probably want to use a [Grid](https://material-ui.com/components/grid/).

**Comment by zer0kool** [comment]
Component built, needs actual links and data

**Comment by josueetcom** [comment]
Sweet! Feel free to create a pull request for it. Separate issues can be filed for filling in the links and data as necessary.

**Comment by josueetcom** [comment]
Unassigning. Please let me know if you'd like to continue working on it.

**Comment by zer0kool** [comment]
Sorry @josueetcom,  I will need some time to review the code. Is this still unfinished?

**Comment by josueetcom** [comment]
@zer0kool Yes, this is still unfinished. I've added some links in the description to get a sense of what to use.

**Comment by josueetcom** [comment]
We could have some repeated links like:
- Add a scholarship
- Browse scholarships

And move these to the bottom:
- About
- Contact

And maybe links to other DreamScholars related stuff, e.g. repo or other informational pages not yet written (e.g. how to join the team, reporting issues, FAQs)

**Comment by josueetcom** [comment]
Use the footers in https://washboard.wsac.wa.gov/login.aspx and https://www.fastweb.com/ as reference
