### ISSUE TITLE
Update Profile Dropdown Menu links

### ISSUE THREAD

**Issue by gonzalo1330** [beyondhb1079/s4us#226]
**Update MenuList links**
Currently the options that are available are not implemented therefore there is no direct link to use.

**To Link**

- [ ] 1. Manage your profile -> edit profile stepper?

- [ ] 2. New -> redirect to scholarship with the `newest` filter applied?

- [ ] 3. Saved -> should redirect to the user bookmarked/saved scholarships `CardList`

- [ ] 4. Applied -> should show the list of scholarships user has selected `Apply` on scholarships list

**Comment by josueetcom** [comment]
I think this was fixed by #507 or something similar. These broken links are hidden behind an experiment
