### ISSUE TITLE
Sorting options: functionality

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#276]
- [x] Ensure a sorting option component exists, or create a basic one if needed with all the sorting options
- [ ] Add any necessary support to [`Scholarships.list()`](https://github.com/beyondhb1079/s4us/blob/main/src/models/base/FirestoreCollection.ts#L29)
- [ ] Add support to the scholarship list page to apply the sorting option

**Comment by gonzalo1330** [comment]
Minimal update of sorting functionality on PR #321 ATM
