### ISSUE TITLE
Public Home page

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#285]
**User Story**
_As a user, I can understand the site's purpose_

- [x] #43
- [x] #284
- [x] #26

**Comment by Jobhdez** [comment]
does this issue entail writing a user story in the homepage? can you please describe this issue a little bit more? thanks

**Comment by josueetcom** [comment]
This is tracking issue for the public facing home page (when a user isn't logged in) which is the landing page of the site. 

We have a Figma design for it here:
https://www.figma.com/file/nwrW3UebcvSWyQZGb5ixNr/DreamScholar?node-id=0%3A1

We haven't quite figured out the wording though (and also the `theme.js` file needs to be updated)
