### ISSUE TITLE
Contact page: Implement a working contact method

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#30]
Are we going to use the form? Or perhaps instead just create an email alias? Either way let's make sure the contact us page actually works.

**Comment by edwingl10** [comment]
I think creating an email alias would be better.

**Comment by josueetcom** [comment]
Yeah an email alias is probably easier too. You could look into setting up a [Google Group](https://groups.google.com/) which serve as a mailing list for us.
