### ISSUE TITLE
Scholarship list: result card component

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#357]
Update the [current results card](https://github.com/beyondhb1079/s4us/blob/197c4710e33aaf6f4edffb023f5dcd8a52d6c181/src/components/ScholarshipList.jsx#L72-L120) to match the [Figma design](https://www.figma.com/file/nwrW3UebcvSWyQZGb5ixNr/DreamScholar?node-id=229%3A6).

- [ ] Refactor the result card as a component that takes in a scholarship as a property so it can be reused in other components.

- [ ] Update card to match Figma design.

**Comment by at-syot** [comment]
Hi @josueetcom, Can i work on this issue ?

**Comment by josueetcom** [comment]
Hi @at-syot, I don't think we've met before. How did you learn about this project? And why are you interested in this issue?

**Comment by at-syot** [comment]
I found your project by searching in github, i want to contribute for open source project.
and your project seem to have a good side impact for people.

**Comment by josueetcom** [comment]
Hmm alright. Sure you can work on this issue if you like.

**Comment by josueetcom** [comment]
@at-syot check out the [README](https://github.com/beyondhb1079/s4us#readme) for setup instructions

**Comment by at-syot** [comment]
OK

**Comment by at-syot** [comment]
Hi @josueetcom
Could you please review this [PR](https://github.com/beyondhb1079/s4us/pull/369).

**Comment by josueetcom** [comment]
@at-syot done. Thank you for your contributions!

**Comment by at-syot** [comment]
HI @josueetcom ,
I updated the PR. Can you check again ?
