### ISSUE TITLE
Scholarship detail card component

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#358]
This is the detail card that appears in the [search page](https://www.figma.com/file/nwrW3UebcvSWyQZGb5ixNr/DreamScholar?node-id=53%3A662) as well as the [detail page](https://www.figma.com/file/nwrW3UebcvSWyQZGb5ixNr/DreamScholar?node-id=194%3A5) that's used when people click on a scholarship link from our site.

**Comment by at-syot** [comment]
Hi @josueetcom can i work on this issue ?

**Comment by josueetcom** [comment]
@at-syot Hmm sure but this one's a little tricky as our Scholarship data model does not yet store/read information related to Eligibility requirements. The only eligibility requirements we plan to support initially are **Majors** and **Grade Level** (which doesn't show up in the Figma design). Technically speaking the data model doesn't store **Organization** yet either though so it might still be alright.

**Comment by at-syot** [comment]
Yeah, and i found there is a bug when pressing on ScholarshipCard also.
Maybe i have to check which point i should start at.

**Comment by josueetcom** [comment]
@at-syot Hmm, thanks for noticing. I filed #377. I don't think it was your change as going to an individual scholarship page itself is broken too. If you want, you can work on that issue first. It'd be good to add a test case to make sure the issue doesn't happen again.

**Comment by at-syot** [comment]
Ok then.
let remove me from this issue then assign me too #377 instead.

**Comment by josueetcom** [comment]
@at-syot I figured out the issue and I'm writing up PR #378. No need to worry about it anymore, but do take a look at the changes I made in #378 so you have an idea of what properties **ScholarshipDetailCard** should expect. I imagine it's roughly the same as **ScholarshipListCard**

**Comment by josueetcom** [comment]
FYI, I've done the refactor in #381. I need it for #341. But I haven't done any styling so it's still the same plain text format it was before.

**Comment by at-syot** [comment]
Hey. I'm back from busy week.
FYI: Starting to work on this issue.

**Comment by josueetcom** [comment]
Great!

**Comment by at-syot** [comment]
Hello, where can i find these fields.
Should i mock in their prop-types ? 

<img width="647" alt="Screen Shot 2564-02-15 at 12 26 05" src="https://user-images.githubusercontent.com/3895283/107908657-2c567b80-6f89-11eb-8434-aea3d21d7568.png">

**Comment by josueetcom** [comment]
@at-syot Hmm, we have yet to save those in our database but we have plans for what they'll look like in #56. Each scholarship will have an `eligibility` field with various eligibility requirements. I think we're using an array of strings for states, majors, and ethnicity and a float value for GPA. You can add the fields to the [ScholarshipData model](https://github.com/beyondhb1079/s4us/blob/main/src/models/Scholarships.ts#L6-L18) and add mock data to the [test data scholarships](https://github.com/beyondhb1079/s4us/blob/main/src/testdata/scholarships.js).

**Comment by at-syot** [comment]
@josueetcom  Thx for more detail and the ref.

**Comment by at-syot** [comment]
@josueetcom PR is ready. 🌝

**Comment by josueetcom** [comment]
@edwingl10 I'm not really seeing the card aspect of the detail card on the site, e.g. https://dreamscholars.org/scholarships/I1qqweqWcPX2iAESAMzy
