### ISSUE TITLE
Smooth login button/avatar transition from Unknown auth

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#42]
Steps to reproduce:
1. Go to the [website](https://dreamerscholars.web.app/)
2. Log in
3. Refresh the page

Expectation: **Login** button shows Profile Avatar

Actuality: It says **Login** for a split second

I'm not sure if this is a bug in our end, in React's end, or if it's just a browser caching issue.

**Comment by josueetcom** [comment]
I think the cause of this was figured out in https://github.com/beyondhb1079/s4us/pull/292#issuecomment-761699395. I think the next steps then are to:
1. Make the **Login** button and Avatar take up the same width so that the nav menu buttons don't change location based on which of the two are rendered.
2. Use a fallback [Avatar](https://material-ui.com/components/avatars/#fallbacks) or some sort of progress indicator while the state of login is being fetched.

**Comment by josueetcom** [comment]
I think we can fix this with the following:
- [ ] Make the Avatar's padding to the left big enough that when the Login button shows it doesn't shift the other items
- [ ] Use a transition/animation like Material UI's [Zoom](https://material-ui.com/components/transitions/#zoom) when the auth state is determined.

**Comment by gonzalo1330** [comment]
Within the user home page PR I believe the issue of the avatar sizing was fixed, should this be something I still increase the size of to match the button width?

**Comment by josueetcom** [comment]
Please separate this fix in its own branch + PR. It'd be better not to have it wait on the user home page PR get merged. They're also unrelated issues.

**Comment by gonzalo1330** [comment]
Done
