### ISSUE TITLE
Public home page: styling

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#43]
Let's make it look more like the mocks

**Comment by gonzalo1330** [comment]
**mocks design**
- [ ] Intro - this seems very redundant to the functionality in ScholarshipsMadeSimpleTab #89 

- [ ] ScholarshipsMadeSimpleTab - finalized waiting for review

- [ ] LearnMore - finalized waiting for review

- [ ] FindScholarshipWorryFree - pending
