### ISSUE TITLE
Add tags field to Scholarship Model

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#438]
It should be an array of strings. Don't forget to add tests.

Files of interest:
https://github.com/beyondhb1079/s4us/blob/main/src/models/Scholarships.ts
https://github.com/beyondhb1079/s4us/blob/main/src/models/Scholarships.test.ts

**Comment by mtwn105** [comment]
Hi @josueetcom 

what is the type of tags field?

**Comment by josueetcom** [comment]
@mtwn105 Please re-read the issue description.

**Comment by at-syot** [comment]
Hello, i'm back.
Can i work on this task ?

**Comment by josueetcom** [comment]
Looks this issue was already fixed by @edwingl10 in #476:
https://github.com/beyondhb1079/s4us/blob/064762bf11aadc26b0c40caece465c7597ac0d64/src/models/Scholarships.ts#L22
