### ISSUE TITLE
Hide currently broken functionality behind experiment guards

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#507]
For preview launch, we don't want to have broken links/functionality across the site. Either remove the broken pieces or guard them using experiments (see #506 for an example).

I think the only functionality that's currently broken is the major filter

**Comment by josueetcom** [comment]
@Jobhdez this issue is **not** closed. #506 only provides an example on how to use experiments. There's still plenty of broken functionality on the website that needs to be experiment guarded.

**Comment by Jobhdez** [comment]
Oh ok.

**Comment by josueetcom** [comment]
I think the only functionality that's currently broken is the major filter

**Comment by josueetcom** [comment]
Hey @Jobhdez, for the sake of time I'm handing this one over to @edwingl10. If you made any progress feel free to share it or take over this issue again.

**Comment by Jobhdez** [comment]
> Hey @Jobhdez, for the sake of time I'm handing this one over to @edwingl10. If you made any progress feel free to share it or take over this issue again.

Ok — sounds good!
