### ISSUE TITLE
Schema design: Scholarship model

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#56]
We need to establish what a Scholarship object consists of and how it will be stored in Firestore.

Some [prior related work](https://github.com/beyondhb1079/undocuscholar-web/blob/master/scholarships/Design.md).

Things to consider:
- Firestore is a NoSQL, document-oriented database. See their [Data model](https://cloud.google.com/firestore/docs/data-model).
- See [Structuring data](https://cloud.google.com/firestore/docs/concepts/structure-data) for tips on how to structure data and [Data types](https://cloud.google.com/firestore/docs/concepts/data-types) for info on what data types are supported.

The expectation here is to come up with the Scholarship model in some form.

**Comment by edwingl10** [comment]
This is what I was thinking for the scholarships:
- id: int
- name: string
- deadline: string
- amount: integer or array 
- description: string
- website: string
- type(academic or sports e.g.): string
- data added: Data and time
- last modified: Date and time
- active: boolean
- eligibility: Map

And for the eligibility map (some scholarships may not have any or all of these keys/values): 
- GPA: float/integer
- major: string
- grade level: integer
- school: string
- location: string
- first gen: boolean
- gender: string

**Comment by josueetcom** [comment]
> * id: int

Hmm, the ID could also be the string generated when you [add a document](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document) 

> * deadline: string

What about using a [Date and time data type](https://cloud.google.com/firestore/docs/concepts/data-types)? I imagine a scholarship that doesn't expire could not set that field. Are there other cases we're missing if we use the date/time type?

> * amount: integer or array

What's the idea behind the arrays? And what about full-ride scholarships? 

> * type(academic or sports e.g.): string

I imagine this is the right type for Firestore but I'm guessing this should be one of a fixed set of values like an [enum](https://www.typescriptlang.org/docs/handbook/enums.html)? 

> * eligibility: Map

I imagine we'd want a class type here in JavaScript/TypeScript

> * GPA: float/integer

Float is probably better

> * major: string

Should this maybe be an array of strings in case multiple majors are eligible?

> * grade level: integer

Should this maybe be an array of integers in case multiple majors are eligible? Also perhaps this would be better served by an [enum](https://www.typescriptlang.org/docs/handbook/enums.html) since "grade" is a very loose term after high school.

> * school: string

Maybe an array of strings?

> * location: string

What is meant by location? State? 

> * gender: string

Probably also best served by an enum

**Comment by edwingl10** [comment]
> Hmm, the ID could also be the string generated when you [add a document](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document)

Oh yeah that would be best

> What about using a [Date and time data type](https://cloud.google.com/firestore/docs/concepts/data-types)? I imagine a scholarship that doesn't expire could not set that field. Are there other cases we're missing if we use the date/time type?

I think date/time type covers all cases

> What's the idea behind the arrays? And what about full-ride scholarships?

The arrays would be for a range (e.g. 500-1000). We could also use a single integer with the max/min amount. For full ride scholarships we could use a string? Unless we want to keep the types the same?

> I imagine this is the right type for Firestore but I'm guessing this should be one of a fixed set of values like an [enum](https://www.typescriptlang.org/docs/handbook/enums.html)?

Yes that would be good. 

> What is meant by location? State?

I was thinking of state. But it might not even be needed since we have the schools eligible

**Comment by josueetcom** [comment]
> > What about using a [Date and time data type](https://cloud.google.com/firestore/docs/concepts/data-types)? I imagine a scholarship that doesn't expire could not set that field. Are there other cases we're missing if we use the date/time type?
> 
> I think date/time type covers all cases

Sweet let's do that
 
> > What's the idea behind the arrays? And what about full-ride scholarships?
> 
> The arrays would be for a range (e.g. 500-1000). We could also use a single integer with the max/min amount. For full ride scholarships we could use a string? Unless we want to keep the types the same?

Ahh I think something that explicitly says the min/max might be better. Here are some other ways to consider:
```ts
{
  "min_amount": 500,
  "max_amount": 1000, // this can match max_amount
  "full_ride": false, // for full ride scholarships the other values would not be set or be 0
}
```

```ts
{
  "amount": {
    "type": "RANGE", // An enum. Could be FIXED (with an "amount" field) or FULL_TUITION (with no other fields)
    "min": 500,
    "max": 100,
  }
}
```
One thing to consider is how queries might need to be structured based on different models. E.g. users may want to look at full ride scholarships only or they may want to look at a range

> > What is meant by location? State?
> 
> I was thinking of state. But it might not even be needed since we have the schools eligible

I'd still keep it in some shape. Scholarships may have certain residential or academic state requirements and that's either impossible or hard to express with schools alone. We might want clarification on which of the two this means (maybe some research into which one is more likely a factor is needed)

**Comment by josueetcom** [comment]
One more field: DACA required

**Comment by edwingl10** [comment]
This is how the updated scholarship model so far: 

id: string
name: string
deadline: date and time
amount: {
	type: enum (fixed, range, full ride)
	min: number
	max: number
}
description: string
website: string
type: enum (academic, sports)
date added: date and time
last modified: date and time
active: boolean 

eligibility: {
	GPA: float
	majors: string[]
	grade level: enum
	schools: string[]
	state: string
	first gen: boolean
	gender: enum (male, female, other)
}
DACA required: enum (unknown, required, not required)

**Comment by josueetcom** [comment]
> state: string

might also need to be a list

> DACA required: enum (unknown, required, not required)

I would put this in the eligibility dictionary

Everything else looks good to me though!

**Comment by edwingl10** [comment]
> Everything else looks good to me though!

sweet, I edited the model above with the suggested changes.

**Comment by josueetcom** [comment]
Re: scholarship model. We've made some changes here:
https://github.com/beyondhb1079/s4us/blob/064762bf11aadc26b0c40caece465c7597ac0d64/src/models/Scholarships.ts#L7-L23

But I'm not entirely convinced that all of those are the right changes. We should revisit this and make changes to the model before our Beta launch.
