### ISSUE TITLE
Scholarship form page: component with basic fields

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#65]
We need some sort of form component for adding a Scholarship. For now the form can be linked at path `/scholarships/create` (or `/scholarships/new`)

What fields exactly the form will have will be determined by the model we come up with in #56

**Comment by edwingl10** [comment]
Information required to input scholarship:
- name
- deadline
- amount
- website

**Comment by josueetcom** [comment]
For the other fields we should consider using:
- [TextField](https://material-ui.com/components/text-fields/) for strings/ints (you should be able to set [input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types) if it has some restriction)
- [Date picker](https://material-ui.com/components/pickers/) for dates
- [Checkboxes](https://material-ui.com/components/checkboxes/) for booleans
- [RadioGroup](https://material-ui.com/components/radio-buttons/) or [Select](https://material-ui.com/components/selects/) or [Autocomplete](https://material-ui.com/components/autocomplete/) for single-choice enums (probably a Select if there's a lot of options)
- [Multiple Select](https://material-ui.com/components/selects/#multiple-select) or a [Multiple Value Autocomplete](https://material-ui.com/components/autocomplete/#multiple-values) for list of enums/strings (the `freeSolo` option allows users to input anything).

**Comment by josueetcom** [comment]
> Information required to input scholarship:
> 
> * name
> * deadline
> * amount
> * website

I think we should also require description as well, this will allow us to show _something_ in the search results besides just the title, amount and deadline. It can also be a place for contributors to specify additional requirements not covered by our scholarship fields.
