### ISSUE TITLE
Apply button showing weird colors on Render

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#672]
**Describe the bug**

**To Reproduce**

1. Go to one of the Render preview URLs for one of the PRs.
2. Click on **Scholarships**
3. Click on a scholarship.
4. The **Apply** button has blue text.

**Expected behavior**

The **Apply** button has white text.

**Screenshots**
![image](https://user-images.githubusercontent.com/8023233/135734170-88b6f3cb-8ee6-42dd-9550-18b6e70b884d.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Chrome OS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] N/A

**Additional context**

Doesn't happen on the main site.

**Comment by josueetcom** [comment]
Quickly inspecting the element on Chrome reveals it might be a clash between the button's variant and color:
![image](https://user-images.githubusercontent.com/8023233/135734207-3393a304-0c60-4b1b-80db-20928f1856bd.png)

**Comment by edwingl10** [comment]
I noticed that this bug is resolved. Not sure what changed but the colors are rendering correctly. 

<img width="465" alt="Screen Shot 2021-11-15 at 3 05 31 PM" src="https://user-images.githubusercontent.com/40483569/141866617-5128474d-4175-48f8-8b29-31adc3410e02.png">
