### ISSUE TITLE
ScholarshipAmount bugs

### ISSUE THREAD

**Issue by edwingl10** [beyondhb1079/s4us#719]
While editing a scholarship, noticed the following. 

1. stored values (intended for backend) show when editing a scholarship. E.g. when editing a scholarship that had an amount type set to `Full Tuition`, and changing it to `varies` shows. 

<img width="499" alt="Screen Shot 2021-11-02 at 8 41 22 PM" src="https://user-images.githubusercontent.com/40483569/140007656-7200b03f-78a1-4073-b5a6-5ccbd9fcbcf5.png">

2. amount values from a previous selection carry on to new selection. E.g. when first choosing the `Fixed` type amount for a scholarship and then changing it to `Varies`, min and max are set to fixed amount you inputted at first.
<img width="492" alt="Screen Shot 2021-11-02 at 8 41 48 PM" src="https://user-images.githubusercontent.com/40483569/140007726-89954c9b-0b05-4231-b24b-2bf33c8b8e71.png">

3. `toString` shows wrong text when adding a new scholarship and only setting the min. 
<img width="779" alt="Screen Shot 2021-11-02 at 8 42 28 PM" src="https://user-images.githubusercontent.com/40483569/140007843-0aba5171-d4c5-4c50-a3f1-287af02e89c6.png">

**Comment by josueetcom** [comment]
The second point doesn't sound like an issue to me 🤔

**Comment by edwingl10** [comment]
> The second point doesn't sound like an issue to me 🤔

True, but it'll help with a certain bug. Like in the case when you edit a bounded range and edit the scholarship to have `fixed` amount. If you try so submit, It'll throw an error that min != max.
