### ISSUE TITLE
Pagination: functionality

### ISSUE THREAD

**Issue by josueetcom** [beyondhb1079/s4us#94]
- [ ] Ensure [pagination](https://material-ui.com/components/pagination/) component exists, or create a basic one if needed
- [ ] Add any necessary support to [`Scholarships.list()`](https://github.com/beyondhb1079/s4us/blob/main/src/models/base/FirestoreCollection.ts#L29)
- [ ] Ensure clicking load more loads more results.

This might be helpful for figuring out the Firestore part of it: https://youtu.be/poqTHxtDXwU

**Comment by josueetcom** [comment]
Relevant: https://youtu.be/poqTHxtDXwU

**Comment by Jobhdez** [comment]
I will start working on the issue as soon as I can.
